# Generated by Django 4.2.6 on 2023-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_tweet_author_remove_tweet_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
