# Generated by Django 4.2.6 on 2023-11-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'community category',
                'verbose_name_plural': 'community categories',
                'db_table': 'community_categories',
            },
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'community', 'verbose_name_plural': 'communities'},
        ),
        migrations.AddField(
            model_name='community',
            name='number_of_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='communities.communitycategory'),
        ),
    ]
