# Generated by Django 4.2.6 on 2023-11-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_community_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='communities.communitycategory'),
        ),
    ]
