# Generated by Django 4.2.6 on 2023-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='communities'),
        ),
    ]
