# Generated by Django 4.2.6 on 2023-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_community_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='communities/static/community-logo'),
        ),
    ]
