# Generated by Django 4.2.6 on 2023-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_community_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
